-- 모든 public 테이블에 RLS 활성화
-- Prisma는 직접 DB 연결(postgres role)을 사용하므로 RLS 영향 없음
-- Supabase PostgREST API를 통한 무단 접근만 차단

ALTER TABLE "Account" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VerificationToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TrainingLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Team" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Comment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Like" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PushSubscription" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Nudge" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LockerNote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SessionTeamAssignment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TrainingSession" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Rsvp" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LateFee" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Feedback" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MatchRules" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CheckIn" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "_EquipmentManagers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Venue" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PlayerSubstitution" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "_TaggedInLogs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Uniform" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TrainingEventComment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EquipmentAssignment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Equipment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CardRecord" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AIInsight" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TrainingEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GoalRecord" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RefereeAssignment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PomVote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "QuarterReferee" ENABLE ROW LEVEL SECURITY;
